ALTER TYPE "PaymentProvider" ADD VALUE IF NOT EXISTS 'FLUTTERWAVE';
ALTER TYPE "PaymentProvider" ADD VALUE IF NOT EXISTS 'HUBTEL';
ALTER TYPE "PaymentProvider" ADD VALUE IF NOT EXISTS 'EXPRESSPAY';
ALTER TYPE "PaymentProvider" ADD VALUE IF NOT EXISTS 'THETELLER';
ALTER TYPE "PaymentProvider" ADD VALUE IF NOT EXISTS 'BANK_TRANSFER';
ALTER TYPE "PaymentProvider" ADD VALUE IF NOT EXISTS 'MOBILE_MONEY';
