ALTER TABLE "Bursar" ALTER COLUMN "sex" DROP DEFAULT;
ALTER TABLE "TeacherInvite" ALTER COLUMN "sex" DROP DEFAULT;
ALTER TABLE "ParentInvite" ALTER COLUMN "sex" DROP DEFAULT;
ALTER TABLE "BursarInvite" ALTER COLUMN "sex" DROP DEFAULT;
