ALTER TABLE "Parent" ADD COLUMN IF NOT EXISTS "sex" "UserSex" NOT NULL DEFAULT 'MALE';
ALTER TABLE "ParentInvite" ADD COLUMN IF NOT EXISTS "sex" "UserSex" NOT NULL DEFAULT 'MALE';
ALTER TABLE "Bursar" ADD COLUMN IF NOT EXISTS "sex" "UserSex" NOT NULL DEFAULT 'MALE';
ALTER TABLE "BursarInvite" ADD COLUMN IF NOT EXISTS "sex" "UserSex" NOT NULL DEFAULT 'MALE';
